spring:
  data:
    cassandra:
      contactpoints: 127.0.0.1
      keyspace-name: message-service
      port: 9042
      keyspace: messageServiceKeyspace
      basepackages: io.missus.messageservice.data.entity